# Generated by Django 2.0.7 on 2018-08-05 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_web', models.URLField()),
                ('title_body', models.TextField()),
                ('title_auther', models.CharField(max_length=20)),
                ('title_num', models.CharField(max_length=1000)),
                ('title_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title_item', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-title_date',),
            },
        ),
    ]
