# Generated by Django 2.0.7 on 2018-07-29 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_web', models.CharField(max_length=200)),
                ('title_body', models.TextField()),
                ('title_auther', models.CharField(max_length=20)),
                ('title_num', models.IntegerField()),
                ('title_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-title_date',),
            },
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostB737',
        ),
    ]
