# Generated by Django 2.0.7 on 2018-07-29 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180729_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_web', models.CharField(max_length=200)),
                ('title_body', models.TextField()),
                ('title_auther', models.CharField(max_length=20)),
                ('title_num', models.IntegerField()),
                ('title_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Item')),
            ],
            options={
                'ordering': ('-title_date',),
            },
        ),
        migrations.DeleteModel(
            name='PostB737',
        ),
        migrations.DeleteModel(
            name='PostFlight',
        ),
    ]
