# Generated by Django 2.0.7 on 2018-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180729_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_num',)},
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.CharField(default='B737', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='item_web',
            field=models.CharField(default='http://', max_length=200),
        ),
    ]
