# Generated by Django 2.0.7 on 2018-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180729_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_web',
            field=models.CharField(max_length=200),
        ),
    ]
