# Generated by Django 2.0.7 on 2018-07-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180730_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_item',
        ),
        migrations.AlterField(
            model_name='post',
            name='title_web',
            field=models.URLField(),
        ),
    ]
