# Generated by Django 2.0.7 on 2018-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180730_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_item',
            field=models.CharField(choices=[('F', 'flight'), ('B', 'b737'), ('P', 'python'), ('R', 'redwine')], default='flight', max_length=20),
        ),
    ]
