# Generated by Django 2.0.7 on 2018-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_title_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_item',
            field=models.CharField(max_length=20),
        ),
    ]
