# Generated by Django 2.0.7 on 2018-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180730_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_num',
            field=models.CharField(max_length=1000),
        ),
    ]
